# Generated by Django 5.2.5 on 2026-05-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_packageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='category',
        ),
    ]
