# Generated by Django 5.2.5 on 2026-05-19 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_remove_destination_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.package'),
        ),
    ]
