# Generated by Django 5.2.5 on 2026-05-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_childern',
            new_name='no_of_children',
        ),
    ]
