# Generated by Django 5.2.5 on 2026-05-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_rename_no_of_childern_booking_no_of_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_adults',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_of_children',
        ),
    ]
