# Generated by Django 5.2.5 on 2026-05-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_packagereview'),
        ('users', '0002_providers_district_providers_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDestinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.destination')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.providers')),
            ],
        ),
    ]
