# Generated by Django 5.2.5 on 2026-05-25 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_providerdestinations'),
        ('users', '0002_providers_district_providers_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_name', models.CharField(max_length=100)),
                ('amount_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_people', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.destination')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.providers')),
            ],
        ),
        migrations.CreateModel(
            name='StayImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stay_images/')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.stays')),
            ],
        ),
    ]
