# Generated by Django 5.2.5 on 2026-05-26 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_stays_stayimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stays',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.providerdestinations'),
        ),
    ]
